# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	Bluetooth_cal \
	General_cal \
	Global_cal \
	Hdmi_cal \
	Headset_cal \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	tzdtcpkctl_b00 \
	tzdtcpkctl_b01 \
	tzdtcpkctl_b02 \
	tzdtcpkctl_b03 \
	tzdtcpkctl_mdt \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tznautilus_b00 \
	tznautilus_b01 \
	tznautilus_b02 \
	tznautilus_b03 \
	tznautilus_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	tztpm_b00 \
	tztpm_b01 \
	tztpm_b02 \
	tztpm_b03 \
	tztpm_mdt \
	tzwidevine_b00 \
	tzwidevine_b01 \
	tzwidevine_b02 \
	tzwidevine_b03 \
	tzwidevine_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mdt \
	mm-qcamera-daemon \
	libpn547_fw \
	sensors_msm8994_so \
	sensors_oem_so \
	libactuator_bu64291gwz \
	libactuator_bu64291gwz_camcorder \
	libactuator_bu64291gwz_camera \
	libactuator_bu64296gwx \
	libactuator_bu64296gwx_camcorder \
	libactuator_bu64296gwx_camera \
	libactuator_dw9714 \
	libactuator_dw9714_camcorder \
	libactuator_dw9714_camera \
	libadsprpc_so \
	libchromatix_imx132_common \
	libchromatix_imx132_cpp_liveshot \
	libchromatix_imx132_cpp_preview \
	libchromatix_imx132_cpp_snapshot \
	libchromatix_imx132_cpp_video \
	libchromatix_imx132_default_video \
	libchromatix_imx132_liveshot \
	libchromatix_imx132_postproc \
	libchromatix_imx132_preview \
	libchromatix_imx132_snapshot \
	libchromatix_imx134_common \
	libchromatix_imx134_cpp_hfr_120 \
	libchromatix_imx134_cpp_hfr_60 \
	libchromatix_imx134_cpp_hfr_90 \
	libchromatix_imx134_cpp_liveshot \
	libchromatix_imx134_cpp_preview \
	libchromatix_imx134_cpp_snapshot \
	libchromatix_imx134_cpp_video \
	libchromatix_imx134_cpp_video_hd \
	libchromatix_imx134_default_video \
	libchromatix_imx134_hfr_120 \
	libchromatix_imx134_hfr_60 \
	libchromatix_imx134_hfr_90 \
	libchromatix_imx134_liveshot \
	libchromatix_imx134_postproc \
	libchromatix_imx134_preview \
	libchromatix_imx134_snapshot \
	libchromatix_imx134_video_hd \
	libchromatix_imx135_common \
	libchromatix_imx135_cpp_hfr_120 \
	libchromatix_imx135_cpp_hfr_60 \
	libchromatix_imx135_cpp_hfr_90 \
	libchromatix_imx135_cpp_liveshot \
	libchromatix_imx135_cpp_preview \
	libchromatix_imx135_cpp_snapshot \
	libchromatix_imx135_cpp_video \
	libchromatix_imx135_default_video \
	libchromatix_imx135_hfr_120 \
	libchromatix_imx135_hfr_60 \
	libchromatix_imx135_hfr_90 \
	libchromatix_imx135_liveshot \
	libchromatix_imx135_postproc \
	libchromatix_imx135_preview \
	libchromatix_imx135_snapshot \
	libchromatix_imx188_common \
	libchromatix_imx188_cpp_liveshot \
	libchromatix_imx188_cpp_preview \
	libchromatix_imx188_cpp_snapshot \
	libchromatix_imx188_cpp_video \
	libchromatix_imx188_default_video \
	libchromatix_imx188_liveshot \
	libchromatix_imx188_postproc \
	libchromatix_imx188_preview \
	libchromatix_imx188_snapshot \
	libchromatix_imx200_common \
	libchromatix_imx200_cpp_hfr_120 \
	libchromatix_imx200_cpp_hfr_60 \
	libchromatix_imx200_cpp_hfr_90 \
	libchromatix_imx200_cpp_liveshot \
	libchromatix_imx200_cpp_preview \
	libchromatix_imx200_cpp_snapshot \
	libchromatix_imx200_cpp_snapshot_hdr \
	libchromatix_imx200_cpp_video \
	libchromatix_imx200_cpp_video_4k \
	libchromatix_imx200_cpp_video_hdr \
	libchromatix_imx200_default_video \
	libchromatix_imx200_hfr_120 \
	libchromatix_imx200_hfr_60 \
	libchromatix_imx200_hfr_90 \
	libchromatix_imx200_liveshot \
	libchromatix_imx200_postproc \
	libchromatix_imx200_preview \
	libchromatix_imx200_snapshot \
	libchromatix_imx200_snapshot_hdr \
	libchromatix_imx200_video_4k \
	libchromatix_imx200_video_hdr \
	libchromatix_imx241_common \
	libchromatix_imx241_cpp_liveshot \
	libchromatix_imx241_cpp_preview \
	libchromatix_imx241_cpp_snapshot \
	libchromatix_imx241_cpp_video \
	libchromatix_imx241_default_video \
	libchromatix_imx241_liveshot \
	libchromatix_imx241_postproc \
	libchromatix_imx241_preview \
	libchromatix_imx241_snapshot \
	libchromatix_imx300_common \
	libchromatix_imx300_cpp_hfr_120 \
	libchromatix_imx300_cpp_hfr_60 \
	libchromatix_imx300_cpp_hfr_90 \
	libchromatix_imx300_cpp_liveshot \
	libchromatix_imx300_cpp_preview \
	libchromatix_imx300_cpp_snapshot \
	libchromatix_imx300_cpp_snapshot_hdr \
	libchromatix_imx300_cpp_video \
	libchromatix_imx300_cpp_video_hdr \
	libchromatix_imx300_default_video \
	libchromatix_imx300_hfr_120 \
	libchromatix_imx300_hfr_60 \
	libchromatix_imx300_hfr_90 \
	libchromatix_imx300_liveshot \
	libchromatix_imx300_postproc \
	libchromatix_imx300_preview \
	libchromatix_imx300_snapshot \
	libchromatix_imx300_snapshot_hdr \
	libchromatix_imx300_video_hdr \
	libflash_pmic \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_isp_modules \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_sensor_debug \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_modules \
	libmmcamera2_vpe_module \
	libmmcamera2_wnr_module \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_faceproc \
	libmmcamera_imglib \
	libmmcamera_imx132 \
	libmmcamera_imx134 \
	libmmcamera_imx135 \
	libmmcamera_imx188 \
	libmmcamera_imx200 \
	libmmcamera_imx241 \
	libmmcamera_imx300 \
	libmmcamera_isp_abf44 \
	libmmcamera_isp_bcc44 \
	libmmcamera_isp_bf_scale_stats46 \
	libmmcamera_isp_bf_stats44 \
	libmmcamera_isp_bg_stats46 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_bpc44 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_clf46 \
	libmmcamera_isp_color_correct46 \
	libmmcamera_isp_color_xform_encoder46 \
	libmmcamera_isp_color_xform_video46 \
	libmmcamera_isp_color_xform_viewfinder46 \
	libmmcamera_isp_cs_stats46 \
	libmmcamera_isp_demosaic44 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder46 \
	libmmcamera_isp_fovcrop_video46 \
	libmmcamera_isp_fovcrop_viewfinder46 \
	libmmcamera_isp_gamma44 \
	libmmcamera_isp_gic46 \
	libmmcamera_isp_gtm46 \
	libmmcamera_isp_hdr46 \
	libmmcamera_isp_hdr_be_stats46 \
	libmmcamera_isp_ihist_stats46 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_ltm44 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff44 \
	libmmcamera_isp_pedestal_correct46 \
	libmmcamera_isp_rs_stats46 \
	libmmcamera_isp_scaler_encoder46 \
	libmmcamera_isp_scaler_video46 \
	libmmcamera_isp_scaler_viewfinder46 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_sub_module \
	libmmcamera_isp_wb46 \
	libmmcamera_ppbase_module \
	libmmcamera_tuning \
	libmmcamera_vpu_module \
	libmmjpeg \
	libmmqjpeg_codec \
	libmmqjpegdma \
	liboemcamera \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	sensors_msm8994_so \
	sensors_oem_so \
	libadsprpc_so
